'use client';
import { use,useEffect,useMemo,useState } from 'react';import { AnimatePresence,motion } from 'framer-motion';import { BarChart3,BookOpen,Edit3,LoaderCircle,Plus,Save,Trash2,X } from 'lucide-react';import { toast } from 'sonner';
import { PageHeader } from '@/components/page-header';import { SemesterTabs } from '@/components/semester-tabs';import { api } from '@/lib/api';import { academicYearBase,buildWorkingWeeks,formatDate,status,statusStyle,type Semester } from '@/lib/portion-utils';
type Subject={id:string;name:string;teacher:string;total_pages:number;total_periods:number;periods_per_week:number;pages_per_week:number;row_version:number};
type Progress={id:string;subject_id:string;week_key:string;month_key:string;week_no:number;date_from:string;date_to:string;period_taken:number;pages_taken:number;remarks:string;row_version:number};
type Payload={class:{id:string;name:string};subjects:Subject[];progress:Progress[];excluded:string[]};
const blank={name:'',teacher:'',totalPages:'',totalPeriods:'',periodsPerWeek:''};
export default function ClassPlanPage({params}:{params:Promise<{id:string}>}){const {id}=use(params);const year=academicYearBase();const [semester,setSemester]=useState<Semester>('SEM-1');const [data,setData]=useState<Payload>();const [loading,setLoading]=useState(true);const [selected,setSelected]=useState('');const [modal,setModal]=useState(false);const [editing,setEditing]=useState<Subject>();const [form,setForm]=useState(blank);const [drafts,setDrafts]=useState<Record<string,Partial<Progress>>>({});const [saving,setSaving]=useState(false);
 async function load(quiet=false){if(!quiet)setLoading(true);try{const next=await api<Payload>(`/api/classes/${id}?year=${year}&semester=${semester}`);setData(next);setSelected(old=>next.subjects.some(s=>s.id===old)?old:next.subjects[0]?.id||'');setDrafts({})}catch(e){toast.error(e instanceof Error?e.message:'Could not load plan')}finally{setLoading(false)}}useEffect(()=>{load()},[id,semester]);
 const weeks=useMemo(()=>buildWorkingWeeks(semester,year,new Set(data?.excluded||[])),[semester,year,data?.excluded]);const subject=data?.subjects.find(s=>s.id===selected);const progress=useMemo(()=>new Map((data?.progress||[]).filter(p=>p.subject_id===selected).map(p=>[p.week_key,p])),[data?.progress,selected]);
 const stats=useMemo(()=>{if(!subject)return {periods:0,pages:0,expected:0,pct:0};const periods=[...progress.values()].reduce((a,p)=>a+Number(p.period_taken),0);const pages=[...progress.values()].reduce((a,p)=>a+Number(p.pages_taken),0);const expected=weeks.length*Number(subject.pages_per_week);return {periods,pages,expected,pct:expected?Math.min(100,Math.round(pages/expected*100)):0}},[subject,progress,weeks]);
 function openAdd(){setEditing(undefined);setForm(blank);setModal(true)}function openEdit(s:Subject){setEditing(s);setForm({name:s.name,teacher:s.teacher,totalPages:String(s.total_pages),totalPeriods:String(s.total_periods),periodsPerWeek:String(s.periods_per_week)});setModal(true)}
 async function saveSubject(e:React.FormEvent){e.preventDefault();setSaving(true);try{await api(`/api/classes/${id}`,{method:'POST',body:JSON.stringify({action:'save-subject',academicYear:year,semester,id:editing?.id,rowVersion:editing?.row_version,name:form.name,teacher:form.teacher,totalPages:Number(form.totalPages),totalPeriods:Number(form.totalPeriods),periodsPerWeek:Number(form.periodsPerWeek)})});toast.success(editing?'Subject updated':'Subject added');setModal(false);await load(true)}catch(e){toast.error(e instanceof Error?e.message:'Save failed')}finally{setSaving(false)}}
 async function remove(s:Subject){if(!confirm(`Delete ${s.name} and all of its weekly progress?`))return;try{await api(`/api/classes/${id}`,{method:'POST',body:JSON.stringify({action:'delete-subject',subjectId:s.id})});toast.success('Subject deleted');await load(true)}catch(e){toast.error(e instanceof Error?e.message:'Delete failed')}}
 function change(key:string,field:'period_taken'|'pages_taken'|'remarks',value:string){setDrafts(d=>({...d,[key]:{...d[key],[field]:field==='remarks'?value:Number(value)}}))}
 async function saveProgress(){if(!subject)return;const changed=weeks.filter(w=>drafts[w.key]);if(!changed.length){toast.info('No weekly changes to save');return}setSaving(true);try{const rows=changed.map(w=>{const current=progress.get(w.key);const d=drafts[w.key]||{};return {weekKey:w.key,monthKey:w.monthKey,weekNo:w.weekNo,dateFrom:w.dateFrom,dateTo:w.dateTo,periodTaken:Number(d.period_taken??current?.period_taken??0),pagesTaken:Number(d.pages_taken??current?.pages_taken??0),remarks:String(d.remarks??current?.remarks??''),rowVersion:current?.row_version||0}});await api(`/api/classes/${id}`,{method:'POST',body:JSON.stringify({action:'save-progress',subjectId:subject.id,rows})});toast.success('Weekly progress saved');await load(true)}catch(e){toast.error(e instanceof Error?e.message:'Progress save failed');await load(true)}finally{setSaving(false)}}
 if(loading)return <main className="page grid min-h-[70vh] place-items-center"><LoaderCircle className="animate-spin text-[#16775d]"/></main>;if(!data)return null;
 return <main className="page"><PageHeader title={data.class.name} subtitle="Subject planning and weekly progress" back="/classes"/><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><SemesterTabs value={semester} onChange={setSemester}/><button onClick={openAdd} className="btn btn-primary"><Plus size={17}/> Add subject</button></div>
 {data.subjects.length===0?<div className="card p-9 text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-emerald-50 text-[#16775d]"><BookOpen/></span><h2 className="display mt-5 text-3xl font-semibold">No subjects yet</h2><p className="muted mt-2 text-sm">Add the first subject for {semester==='SEM-1'?'Semester 1':'Semester 2'}.</p><button onClick={openAdd} className="btn btn-primary mt-6"><Plus size={17}/> Add subject</button></div>:<div className="grid items-start gap-5 lg:grid-cols-[300px_1fr]">
  <aside className="card p-3"><p className="eyebrow px-2 pb-3 pt-2">Subjects</p><div className="space-y-2">{data.subjects.map(s=><button onClick={()=>setSelected(s.id)} key={s.id} className={`w-full rounded-2xl p-3 text-left transition ${selected===s.id?'bg-[#16775d] text-white shadow-lg':'hover:bg-emerald-50'}`}><div className="flex items-center justify-between gap-2"><strong className="truncate text-sm">{s.name}</strong><span className={`pill !px-2 !py-1 text-[9px] ${selected===s.id?'bg-white/15':'bg-stone-100 text-stone-500'}`}>{Number(s.pages_per_week).toFixed(1)} pg/wk</span></div><p className={`mt-1 truncate text-xs ${selected===s.id?'text-white/70':'muted'}`}>{s.teacher}</p></button>)}</div></aside>
  {subject&&<section className="space-y-5"><div className="card p-5 md:p-6"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Selected subject</p><h2 className="display mt-1 text-3xl font-semibold">{subject.name}</h2><p className="muted mt-1 text-sm">{subject.teacher} · {subject.periods_per_week} periods/week</p></div><div className="flex gap-2"><button onClick={()=>openEdit(subject)} aria-label="Edit subject" className="btn btn-secondary !h-10 !min-h-10 !w-10 !p-0"><Edit3 size={16}/></button><button onClick={()=>remove(subject)} aria-label="Delete subject" className="btn btn-secondary !h-10 !min-h-10 !w-10 !p-0 text-red-600"><Trash2 size={16}/></button></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-stone-100"><motion.div initial={{width:0}} animate={{width:`${stats.pct}%`}} className="h-full rounded-full bg-[#16775d]"/></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Stat label="Periods" value={stats.periods}/><Stat label="Pages" value={stats.pages}/><Stat label="Progress" value={`${stats.pct}%`}/></div></div>
   <div className="card overflow-hidden"><div className="border-b border-[#dfe5df] p-5"><div className="flex items-center gap-2"><BarChart3 size={18} className="text-[#16775d]"/><h3 className="display text-2xl font-semibold">Weekly progress</h3></div><p className="muted mt-1 text-xs">Record what was completed and the last page reached in remarks.</p></div><div className="space-y-3 p-3 md:p-5">{weeks.map(w=>{const row=progress.get(w.key),d=drafts[w.key]||{};const actual=Number(d.pages_taken??row?.pages_taken??0);const st=status(actual,Number(subject.pages_per_week));return <div key={w.key} className="rounded-2xl border border-[#dfe5df] bg-white p-4"><div className="flex items-start justify-between gap-2"><div><strong className="text-sm">Week {w.weekNo} · {w.monthLabel}</strong><p className="muted mt-1 text-[11px]">{formatDate(w.dateFrom)} – {formatDate(w.dateTo)} · {w.workingDates.length} working days</p></div><span className={`pill ${statusStyle(st)}`}>{st}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-[120px_120px_1fr]"><Field label="Periods" type="number" value={String(d.period_taken??row?.period_taken??'')} onChange={v=>change(w.key,'period_taken',v)} placeholder="0"/><Field label="Pages covered" type="number" value={String(d.pages_taken??row?.pages_taken??'')} onChange={v=>change(w.key,'pages_taken',v)} placeholder="0"/><Field label="Remarks / last page" value={String(d.remarks??row?.remarks??'')} onChange={v=>change(w.key,'remarks',v)} placeholder="e.g. Reached page 48"/></div></div>})}</div><div className="sticky bottom-0 border-t border-[#dfe5df] bg-[#fffef9]/95 p-4 backdrop-blur"><button disabled={saving} onClick={saveProgress} className="btn btn-primary w-full">{saving?<LoaderCircle className="animate-spin" size={17}/>:<Save size={17}/>} Save weekly status</button></div></div>
  </section>}
 </div>}
 <AnimatePresence>{modal&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={()=>setModal(false)} className="fixed inset-0 z-50 grid place-items-end bg-black/40 backdrop-blur-sm sm:place-items-center sm:p-4"><motion.form initial={{y:40}} animate={{y:0}} exit={{y:40}} onSubmit={saveSubject} onMouseDown={e=>e.stopPropagation()} className="max-h-[92vh] w-full overflow-auto rounded-t-[28px] bg-[#fffef9] p-6 sm:max-w-lg sm:rounded-[28px]"><div className="flex items-center justify-between"><h2 className="display text-3xl font-semibold">{editing?'Edit subject':'Add a subject'}</h2><button type="button" onClick={()=>setModal(false)} className="btn btn-secondary !h-10 !min-h-10 !w-10 !p-0"><X size={17}/></button></div><div className="mt-6 grid gap-4"><Field label="Subject name" value={form.name} onChange={v=>setForm({...form,name:v})} placeholder="e.g. Fiqh" required/><Field label="Teacher name" value={form.teacher} onChange={v=>setForm({...form,teacher:v})} placeholder="Teacher or initials" required/><div className="grid grid-cols-2 gap-3"><Field label="Total pages" type="number" value={form.totalPages} onChange={v=>setForm({...form,totalPages:v})} placeholder="0" required/><Field label="Total periods" type="number" value={form.totalPeriods} onChange={v=>setForm({...form,totalPeriods:v})} placeholder="0" required/></div><Field label="Periods per week" type="number" value={form.periodsPerWeek} onChange={v=>setForm({...form,periodsPerWeek:v})} placeholder="0" required/><div className="rounded-2xl bg-emerald-50 p-3 text-xs text-emerald-800">Pages per period and pages per week are calculated automatically.</div><button disabled={saving} className="btn btn-primary w-full">{saving?<LoaderCircle className="animate-spin" size={17}/>:<Save size={17}/>} Save subject</button></div></motion.form></motion.div>}</AnimatePresence>
 </main>}
function Field({label,value,onChange,placeholder,type='text',required=false}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;type?:string;required?:boolean}){return <label className="block"><span className="mb-1.5 block text-[10px] font-extrabold uppercase tracking-wider text-stone-500">{label}</span><input className="input !min-h-10 !rounded-xl !px-3 !py-2 text-sm" type={type} min={type==='number'?0:undefined} step={type==='number'?'any':undefined} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} required={required}/></label>}
function Stat({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl bg-[#f3f6f2] p-3"><strong className="display block text-xl">{value}</strong><span className="muted text-[10px] font-bold uppercase tracking-wide">{label}</span></div>}
