export type Semester = 'SEM-1' | 'SEM-2';
export type CalendarDay = { value:string; day:number; monthLabel:string };
export type WorkingWeek = { key:string; monthKey:string; monthLabel:string; weekNo:number; dateFrom:string; dateTo:string; workingDates:string[] };
export const SEMESTER_LABELS:Record<Semester,string[]> = { 'SEM-1':['June','July','August','September','October','November'], 'SEM-2':['November','December','January','February','March','April','May'] };
export function academicYearBase(now=new Date()){ return now.getMonth()<5?now.getFullYear()-1:now.getFullYear(); }
export function iso(d:Date){ return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
export function parseLocal(value:string){ const [y,m,d]=value.split('-').map(Number); return new Date(y,m-1,d); }
export function formatMonthDay(value:string){ const [month,day]=value.split('-').map(Number); return `${day} ${new Date(2000,month-1,1).toLocaleDateString('en',{month:'short'})}`; }
export function semesterRange(semester:Semester,year:number){ return semester==='SEM-1'?{start:new Date(year,5,1),end:new Date(year,10,30)}:{start:new Date(year,10,1),end:new Date(year+1,4,31)}; }
const MONTH_NUMBER:Record<string,number>={January:1,February:2,March:3,April:4,May:5,June:6,July:7,August:8,September:9,October:10,November:11,December:12};
const MONTH_LENGTH:Record<string,number>={January:31,February:29,March:31,April:30,May:31,June:30,July:31,August:31,September:30,October:31,November:30,December:31};
export function semesterDays(semester:Semester){ return SEMESTER_LABELS[semester].flatMap(monthLabel=>Array.from({length:MONTH_LENGTH[monthLabel]},(_,index)=>{const day=index+1;return {value:`${String(MONTH_NUMBER[monthLabel]).padStart(2,'0')}-${String(day).padStart(2,'0')}`,day,monthLabel};})); }
export function buildWorkingWeeks(semester:Semester,_year:number,excluded:Set<string>){ const out:WorkingWeek[]=[]; for(const monthLabel of SEMESTER_LABELS[semester]){const monthKey=String(MONTH_NUMBER[monthLabel]).padStart(2,'0');const length=MONTH_LENGTH[monthLabel];for(let weekNo=1,startDay=1;startDay<=length;weekNo++,startDay+=7){const endDay=Math.min(startDay+6,length);const dateFrom=`${monthKey}-${String(startDay).padStart(2,'0')}`;const dateTo=`${monthKey}-${String(endDay).padStart(2,'0')}`;const workingDates=Array.from({length:endDay-startDay+1},(_,index)=>`${monthKey}-${String(startDay+index).padStart(2,'0')}`).filter(value=>!excluded.has(value));out.push({key:`${semester}-${monthKey}-WK-${weekNo}`,monthKey,monthLabel,weekNo,dateFrom,dateTo,workingDates});}}return out; }
export function status(actual:number,expected:number){ if(actual===0)return 'Pending';if(actual<expected*.95)return 'Behind';if(actual>expected*1.05)return 'Ahead';return 'On track'; }
export function statusStyle(value:string){ return value==='Behind'?'bg-red-50 text-red-700':value==='Ahead'?'bg-blue-50 text-blue-700':value==='On track'?'bg-emerald-50 text-emerald-700':'bg-stone-100 text-stone-600'; }
