'use client';
import Link from 'next/link';import { useEffect,useState } from 'react';import { AnimatePresence,motion } from 'framer-motion';import { ArrowRight,BookOpen,LoaderCircle,Plus,Sparkles,X } from 'lucide-react';import { toast } from 'sonner';import { PageHeader } from '@/components/page-header';import { api } from '@/lib/api';
type ClassRow={id:string;name:string;created_at:string};
export default function ClassesPage(){const [classes,setClasses]=useState<ClassRow[]>([]);const [loading,setLoading]=useState(true);const [open,setOpen]=useState(false);const [name,setName]=useState('');const [saving,setSaving]=useState(false);const load=()=>api<{classes:ClassRow[]}>('/api/classes').then(r=>setClasses(r.classes)).catch(e=>toast.error(e.message)).finally(()=>setLoading(false));useEffect(()=>{load()},[]);
 async function add(e:React.FormEvent){e.preventDefault();setSaving(true);try{await api('/api/classes',{method:'POST',body:JSON.stringify({name})});setOpen(false);setName('');toast.success('Class added');await load()}catch(e){toast.error(e instanceof Error?e.message:'Could not add class')}finally{setSaving(false)}}
 return <main className="page"><PageHeader title="Choose your class" subtitle="Every class has its own subjects, plans and weekly progress."/><div className="mb-6 flex items-center justify-between"><div><p className="eyebrow">Class directory</p><p className="muted mt-1 text-sm">{classes.length} {classes.length===1?'class':'classes'} available</p></div>{classes.length>0&&<button onClick={()=>setOpen(true)} className="btn btn-primary"><Plus size={17}/> Add class</button>}</div>
 {loading?<div className="grid h-72 place-items-center"><LoaderCircle className="animate-spin text-[#16775d]"/></div>:classes.length===0?<div className="card mx-auto max-w-xl p-8 text-center md:p-12"><span className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-emerald-50 text-[#16775d]"><BookOpen size={28}/></span><h2 className="display mt-5 text-3xl font-semibold">Add your first class</h2><p className="muted mx-auto mt-2 max-w-sm text-sm leading-6">There are no classes yet. Start by entering the class name your team will recognise.</p><button onClick={()=>setOpen(true)} className="btn btn-primary mt-6"><Plus size={18}/> Add your class</button></div>:<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{classes.map((c,i)=><motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:i*.05}} key={c.id}><Link href={`/classes/${c.id}`} className="card group flex min-h-36 flex-col justify-between p-5 transition hover:-translate-y-1 hover:border-emerald-200"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-emerald-50 font-extrabold text-[#16775d]">{c.name.slice(0,2).toUpperCase()}</span><ArrowRight size={18} className="muted transition group-hover:translate-x-1 group-hover:text-[#16775d]"/></div><div><h2 className="display text-2xl font-semibold">{c.name}</h2><p className="muted mt-1 text-xs">Open portion plan</p></div></Link></motion.div>)}</div>}
 {classes.length>0&&<p className="muted mt-7 flex items-center justify-center gap-1.5 text-center text-xs"><Sparkles size={13}/> Don’t find your class? Add it by entering its name.</p>}
 <AnimatePresence>{open&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 grid place-items-end bg-black/35 p-0 backdrop-blur-sm sm:place-items-center sm:p-4" onMouseDown={()=>setOpen(false)}><motion.form initial={{y:40,opacity:0}} animate={{y:0,opacity:1}} exit={{y:40,opacity:0}} onSubmit={add} onMouseDown={e=>e.stopPropagation()} className="w-full rounded-t-[28px] bg-[#fffef9] p-6 shadow-2xl sm:max-w-md sm:rounded-[28px]"><div className="flex items-center justify-between"><h2 className="display text-3xl font-semibold">Add a class</h2><button type="button" onClick={()=>setOpen(false)} className="btn btn-secondary !h-10 !min-h-10 !w-10 !p-0"><X size={17}/></button></div><label className="mt-6 block text-xs font-extrabold uppercase tracking-wider">Class name</label><input autoFocus className="input mt-2" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Wafy 3rd Year" minLength={2} maxLength={60} required/><button disabled={saving} className="btn btn-primary mt-4 w-full">{saving?<LoaderCircle className="animate-spin" size={18}/>:<Plus size={18}/>} Create class</button></motion.form></motion.div>}</AnimatePresence>
 </main>}
